services:
  db:
    image: postgres:15
    container_name: sca_db_local
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=sca_db
      - POSTGRES_USER=sca_user
      - POSTGRES_PASSWORD=sca_password
    ports:
      - "5432:5432"

volumes:
  postgres_data: